apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-api
  template:
    metadata:
      labels:
        app: deployment-api
    spec:
      containers:
      - name: deployment-api
        image: deployment-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80