replicaCount: 2

image:
  repository: deployment-api
  tag: "latest"
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  nodePort: 30007

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false

httpRoute:
  enabled: false

resources: {}

autoscaling:
  enabled: false