replicaCount: 2

# image:
#   repository: deployment-api
#   tag: "latest"
#   pullPolicy: Never

image:
  repository: deployment-api
  tag: "v1"
  pullPolicy: Never

env:
  APP_VERSION: "v1"

service:
  type: NodePort
  port: 80
  nodePort: 30007

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false

httpRoute:
  enabled: false

resources: {}

autoscaling:
  enabled: false