apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deployment-api
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm/deployment-api
      sourceRef:
        kind: GitRepository
        name: deployment-repo
        namespace: flux-system
  values:
    replicaCount: 2
    image:
      repository: deployment-api
      tag: "v2"
      pullPolicy: Never
    env:
      APP_VERSION: "v2"