apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment-api.fullname" . }}
  labels:
    app: {{ include "deployment-api.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "deployment-api.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}